spring.application.name=soletrack


open-banking.active-provider=enableBanking

# Enable Banking
#https://enablebanking.com
enable-banking.base-url=https://api.enablebanking.com
enable-banking.app-id=d33420c1-17d5-49e7-a9c1-5291687c4031
enable-banking.key-path=classpath:enablebanking/sandbox/sandbox_private.pem
enable-banking.redirect-url=http://localhost:8080/callback

#https://enablebanking.com/docs/api/sandbox/#s-pankki
enable-banking.aspsp.name=S-Pankki
enable-banking.aspsp.country=FI